(library
 (name prover_lib)
 (modules
  types
  pretty
  subst
  unif
  match
  clause
  fof
  clausify
  ordering
  feature_vector
  discrimination_index
  term_index
  legacy_resolution
  resolution
  tptp_parser
  tptp_lexer
  tptp_frontend
  prover)
 (libraries unix))

(menhir
 (modules tptp_parser)
 (infer true))

(ocamllex tptp_lexer)
