(executable
 (name main)
 (modules header main sites)
 (libraries prover_lib unix dune-site.plugins)
 (link_flags (:standard -ccopt -static)))

(generate_sites_module
 (module sites)
 (sites vip))

(install
 (section (site (vip sounds)))
 (files unsat.mp3 timeout.mp3))

(install
 (section bin)
 (files (main.exe as vip) (main.exe as ip)))
