(test
 (name test_parser)
 (libraries prover_lib alcotest))

(test
 (name test_clausify)
 (libraries prover_lib alcotest))

(test
 (name test_unify)
 (libraries prover_lib alcotest))

(test
 (name test_match_subsume)
 (libraries prover_lib alcotest))

(test
 (name test_fvi)
 (libraries prover_lib alcotest))

(test
 (name test_resolution)
 (libraries prover_lib alcotest))

(test
 (name test_sat_probe)
 (libraries prover_lib alcotest))

(test
 (name test_ordering)
 (libraries prover_lib alcotest))

(test
 (name test_indexes)
 (libraries prover_lib alcotest))
